### ISSUE TITLE
Link Checker CI - Tracking & Improvements

### ISSUE THREAD

**Issue by naher94** [naher94/rehanbutt.com#664]
## Overview

Automated GitHub Action that runs monthly (1st of each month at 9am UTC) scanning the built Jekyll site for dead links, creating an issue report when errors are found.

- Tool: [lychee](https://lychee.cli.rs) via [`lycheeverse/lychee-action@v2`](https://github.com/lycheeverse/lychee-action)
- Workflow: `.github/workflows/link-check.yml`
- Trigger: scheduled (monthly), manual `workflow_dispatch`, or `repository_dispatch`

## Setup History

| Issue | What happened |
|-------|--------------|
| #841 | First attempt — scanned raw source files instead of the built `_site`, so Liquid templates like `{{page.url}}` showed up as broken `file://` links |
| #862 | Closer — scanned `_site` but still had noise from unbuilt templates and missing exclusions |
| Current | Builds the Jekyll site first, then scans `_site` only. Profile URLs for LinkedIn, CodePen, Instagram, and Threads excluded to avoid rate-limit false positives |

## Current Excluded URLs

These are excluded because the services rate-limit or block automated crawlers:

- `^https://www\.linkedin\.com/in/rehan-butt/`
- `^https://codepen\.io/rehanbutt`
- `^https://instagram\.com/naher94`
- `^https://www\.threads\.net/@naher94` (profile)
- `^https://threads\.net/intent/` (share/intent links — #1124)

## Known Issues & Open Items

- [ ] **Link count fluctuation** (#1115, #1090) — Total link count dropped from ~2787 (#1039) to 219 (#1090) then back to ~2992 (#1124). Needs investigation — could be a lychee version difference, caching behavior, or build output changes
- [ ] **Checkbox output format** — lychee's checklist/checkbox output doesn't render correctly in GitHub issues ([lychee-action#274](https://github.com/lycheeverse/lychee-action/issues/274), [comment](https://github.com/lycheeverse/lychee-action/issues/274#issuecomment-2974537782))
- [x] ~~Custom accepted status codes~~ — Added `--accept 100..=103,200..=299,403` to reduce false positives ([lychee#1661](https://github.com/lycheeverse/lychee/issues/1661))
- [x] ~~Cache support~~ — [lychee-action#278](https://github.com/lycheeverse/lychee-action/issues/278)
- [x] ~~Threads intent URLs flagged as 429~~ — Excluded `threads.net/intent/` pattern (#1124)

## Related Reports

Open reports to triage:
- #1039
- #1090
- #1124

Closed reports (resolved or superseded):
- #841, #862, #1118, #1119, #1120

**Comment by naher94** [comment]
does not seem to work

**Comment by naher94** [comment]
Add a GitHub action that checks for broken links on a weekly basis

**Comment by naher94** [comment]
This works but check the whole repo not just the _site directory
```
name: Link Checker

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write # required for peter-evans/create-issue-from-file
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build --trace

      - name: Filter files to check (include _site, exclude _site/css and _site/img)
        run: |
          # Find all files in _site, but exclude _site/css and _site/img
          find ./_site -type f | grep -vE '/(css|img)/' > files-to-check.txt
          cat files-to-check.txt

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          fail: false
          files: './files-to-check.txt'
          base: https://rehanbutt.com

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Dead Links Found - Link Checker Report
          content-filepath: ./lychee/out.md
```
