### ISSUE TITLE
Code Cleaning - Remove all unused Foundation stuff

### ISSUE THREAD

**Issue by naher94** [naher94/rehanbutt.com#712]
`js` and `_sass` looks to have a bunch that can be removed.
https://githubnext.com/projects/repo-visualization/

<img width="756" alt="Screenshot 2024-03-24 at 10 38 47 AM" src="https://github.com/naher94/rehanbutt.com/assets/7800629/1ee6950e-546b-4aee-bec5-a783a89f46da">

`_sass/forms`,`_sass/prototype` are probably save to remove. Most of `_sass/components` are probably save to remove as well, pretty sure I am using `_responsive-embed.scss` though

Pages to review before merging and items to check for link clicks, hover effects, easter egg banner / badge, footer hover, on page typography.

- [ ] Desktop
  - [x] Home
    - [x] Link Clicks
    - [x] Hover Effects
    - [x] Easter Egg Banner
    - [x] Easter Egg Toast
    - [x] On Page Typography 
  - [ ] About
    - [x] Link Clicks
    - [x] Hover Effects
    - [ ] Easter Egg Banner https://github.com/naher94/rehanbutt.com/issues/726
    - [x] Easter Egg Toast
    - [x] On Page Typography 
  - [x] Project Page
    - [x] Link Clicks
    - [x] Hover Effects
    - [x] Easter Egg Banner
    - [x] Easter Egg Toast
    - [x] On Page Typography 
  - [ ] Project Page - Hero
    - [x] Link Clicks
    - [x] Hover Effects
    - [x] Easter Egg Banner
    - [ ] Easter Egg Toast https://github.com/naher94/rehanbutt.com/issues/726
    - [x] On Page Typography 
  - [x] Resources
    - [x] Link Clicks
    - [x] Hover Effects
    - [x] Easter Egg Banner
    - [x] Easter Egg Toast
    - [x] On Page Typography 
  - [x] Resource Collection
    - [x] Link Clicks
    - [x] Hover Effects
    - [x] Easter Egg Banner
    - [x] Easter Egg Toast
    - [x] On Page Typography 
  - [x] Article
    - [x] Link Clicks
    - [x] Hover Effects
    - [x] Easter Egg Banner
    - [x] Easter Egg Toast
    - [x] On Page Typography 
  - [ ] Photography
    - [x] Link Clicks
    - [x] Hover Effects
    - [x] Easter Egg Banner
    - [ ] Easter Egg Toast https://github.com/naher94/rehanbutt.com/issues/726
    - [x] On Page Typography
  - [x] Easter Egg Vault
    - [x] Link Clicks
    - [x] Hover Effects
    - [x] Easter Egg Banner
    - [x] Easter Egg Toast
    - [x] On Page Typography 
- [ ] Mobile
  - [x] Home
    - [x] Link Clicks
    - [x] Hover Effects
    - [x] Easter Egg Banner
    - [x] Easter Egg Toast
    - [x] On Page Typography 
  - [ ] About
    - [x] Link Clicks
    - [x] Hover Effects
    - [ ] Easter Egg Banner https://github.com/naher94/rehanbutt.com/issues/726
    - [x] Easter Egg Toast
    - [x] On Page Typography 
  - [x] Project Page
    - [x] Link Clicks
    - [x] Hover Effects
    - [x] Easter Egg Banner
    - [x] Easter Egg Toast
    - [x] On Page Typography 
  - [ ] Project Page - Hero
    - [x] Link Clicks
    - [x] Hover Effects
    - [x] Easter Egg Banner
    - [ ] Easter Egg Toast https://github.com/naher94/rehanbutt.com/issues/726
    - [x] On Page Typography 
  - [x] Resources
    - [x] Link Clicks
    - [x] Hover Effects
    - [x] Easter Egg Banner
    - [x] Easter Egg Toast
    - [x] On Page Typography 
  - [x] Resource Collection
    - [x] Link Clicks
    - [x] Hover Effects
    - [x] Easter Egg Banner
    - [x] Easter Egg Toast
    - [x] On Page Typography 
  - [x] Article
    - [x] Link Clicks
    - [x] Hover Effects
    - [x] Easter Egg Banner
    - [x] Easter Egg Toast
    - [x] On Page Typography 
  - [ ] Photography
    - [x] Link Clicks
    - [x] Hover Effects
    - [x] Easter Egg Banner
    - [ ] Easter Egg Toast https://github.com/naher94/rehanbutt.com/issues/726
    - [x] On Page Typography 
  - [x] Easter Egg Vault
    - [x] Link Clicks
    - [x] Hover Effects
    - [x] Easter Egg Banner
    - [x] Easter Egg Toast
    - [x] On Page Typography

**Comment by naher94** [comment]
`_sass/forms`,`_sass/prototype` are probably save to remove. Most of `_sass/components` are probably save to remove as well, pretty sure I am using `_responsive-embed.scss` though
